'use strict'

export const SEARCH_COMMENTS = 'SEARCH_COMMENTS'
export const SEARCH_POST = 'SEARCH_POST'
export const PUBLISH_NEW_COMMENT = 'PUBLISH_NEW_COMMENT'
export const PUBLISH_EDIT_COMMENT = 'PUBLISH_EDIT_COMMENT'
