'use strict'

export const SEARCH_POSTS = 'SEARCH_POSTS'
export const SEARCH_CATEGORIES = 'SEARCH_CATEGORIES'
export const SEARCH_POSTS_CATEGORY = 'SEARCH_POSTS_CATEGORY'
export const VOTE_UP_POST = 'VOTE_UP_POST'
export const VOTE_DOWN_POST = 'VOTE_DOWN_POST'
export const DELETE_POST = 'DELETE_POST'
